version: '3.8'

services:
  php:
    build: ./docker
    container_name: allman-codesniffer
    volumes:
      - .:/app
      - composer-cache:/root/.composer
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

volumes:
  composer-cache: